repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
-   repo: https://github.com/python-poetry/poetry
    rev: "2.1.2"
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
