"""init: create Project table

Revision ID: 624d89855ea6
Revises:
Create Date: 2025-05-05 12:03:12.871436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "624d89855ea6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("header_url", sa.String(), nullable=True),
        sa.Column("cover_url", sa.String(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_index(
        op.f("ix_project_created_at"), "project", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_project_end_date"), "project", ["end_date"], unique=False)
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.create_index(op.f("ix_project_owner_id"), "project", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_project_start_date"), "project", ["start_date"], unique=False
    )
    op.create_index(
        op.f("ix_project_updated_at"), "project", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_updated_at"), table_name="project")
    op.drop_index(op.f("ix_project_start_date"), table_name="project")
    op.drop_index(op.f("ix_project_owner_id"), table_name="project")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_index(op.f("ix_project_end_date"), table_name="project")
    op.drop_index(op.f("ix_project_created_at"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
