"""FIX: Update String length

Revision ID: 98083b322359
Revises: b0f3df50b124
Create Date: 2025-05-08 20:12:06.193100

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "98083b322359"
down_revision: Union[str, None] = "b0f3df50b124"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
