"""FIXED: Update project_tag_association

Revision ID: b0f3df50b124
Revises: f3a4e14ddfe1
Create Date: 2025-05-05 17:06:29.533964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0f3df50b124"
down_revision: Union[str, None] = "f3a4e14ddfe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_tag_association",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("tag_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_project_tag_association_project_id_project"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name=op.f("fk_project_tag_association_tag_id_tag")
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "tag_id", name=op.f("pk_project_tag_association")
        ),
    )
    op.create_index(
        op.f("ix_project_tag_association_created_at"),
        "project_tag_association",
        ["created_at"],
        unique=False,
    )
    op.drop_table("project_tag_association_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_tag_association_table",
        sa.Column("project_id", sa.VARCHAR(), nullable=False),
        sa.Column("tag_id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="fk_project_tag_association_table_project_id_project",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name="fk_project_tag_association_table_tag_id_tag"
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "tag_id", name="pk_project_tag_association_table"
        ),
    )
    op.drop_index(
        op.f("ix_project_tag_association_created_at"),
        table_name="project_tag_association",
    )
    op.drop_table("project_tag_association")
    # ### end Alembic commands ###
