"""UPDATE: add attachment and tag

Revision ID: f3a4e14ddfe1
Revises: 624d89855ea6
Create Date: 2025-05-05 14:28:07.487458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3a4e14ddfe1"
down_revision: Union[str, None] = "624d89855ea6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
    )
    op.create_index(op.f("ix_tag_created_at"), "tag", ["created_at"], unique=False)
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=False)
    op.create_index(op.f("ix_tag_owner_id"), "tag", ["owner_id"], unique=False)
    op.create_index(op.f("ix_tag_updated_at"), "tag", ["updated_at"], unique=False)
    op.create_table(
        "attachment",
        sa.Column("filename", sa.String(length=128), nullable=False),
        sa.Column("file_type", sa.String(length=10), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_attachment_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment")),
        sa.UniqueConstraint("checksum", name=op.f("uq_attachment_checksum")),
        sa.UniqueConstraint("url", name=op.f("uq_attachment_url")),
    )
    op.create_index(
        op.f("ix_attachment_created_at"), "attachment", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_attachment_file_type"), "attachment", ["file_type"], unique=False
    )
    op.create_index(
        op.f("ix_attachment_filename"), "attachment", ["filename"], unique=False
    )
    op.create_table(
        "project_tag_association_table",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("tag_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_project_tag_association_table_project_id_project"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
            name=op.f("fk_project_tag_association_table_tag_id_tag"),
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "tag_id", name=op.f("pk_project_tag_association_table")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_tag_association_table")
    op.drop_index(op.f("ix_attachment_filename"), table_name="attachment")
    op.drop_index(op.f("ix_attachment_file_type"), table_name="attachment")
    op.drop_index(op.f("ix_attachment_created_at"), table_name="attachment")
    op.drop_table("attachment")
    op.drop_index(op.f("ix_tag_updated_at"), table_name="tag")
    op.drop_index(op.f("ix_tag_owner_id"), table_name="tag")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_index(op.f("ix_tag_created_at"), table_name="tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
